version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - VISION_MODEL=${VISION_MODEL:-openai/gpt-4-vision-preview}
      - STRUCTURING_MODEL=${STRUCTURING_MODEL:-openai/gpt-4}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./app:/app/app # For development - mount app directory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
